import { useEffect, useMemo, useRef, useState } from 'react'
import p5 from 'p5'
import './P5Lab.css'

type P5LabProps = { theme: 'dark' | 'light' }
type PatternName = 'flow field' | 'orbit bloom' | 'noise ribbons'

type P5Settings = {
  pattern: PatternName
  seed: number
  density: number
  speed: number
  scale: number
  complexity: number
  strokeWeight: number
  hue: number
  colorSpread: number
  trails: number
}

const OSA_DEFAULT_SEED = 240519
const PATTERNS: PatternName[] = ['flow field', 'orbit bloom', 'noise ribbons']

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}

function wrapHue(value: number) {
  return ((value % 360) + 360) % 360
}

function drawPattern(
  p: p5,
  settings: P5Settings,
  theme: P5LabProps['theme'],
  clearBeforeDrawing: boolean,
) {
  const isDark = theme === 'dark'
  const background = isDark ? [225, 30, 8] : [215, 12, 98]
  const foreground = isDark ? [270, 5, 98] : [215, 45, 17]
  const backgroundAlpha = clearBeforeDrawing ? 1 : 1 - (settings.trails / 100) * 0.94
  const count = Math.round(24 + settings.density * 2.35)
  const time = p.frameCount * settings.speed * 0.00012
  const sizeMultiplier = 0.25 + settings.scale / 55
  const noiseFrequency = 0.0015 + settings.complexity * 0.00014

  p.background(background[0], background[1], background[2], backgroundAlpha)
  p.randomSeed(settings.seed)
  p.noiseSeed(settings.seed)
  p.strokeCap(p.ROUND)
  p.strokeWeight(settings.strokeWeight)

  if (settings.pattern === 'flow field') {
    for (let index = 0; index < count; index += 1) {
      const x = p.random(p.width)
      const y = p.random(p.height)
      const field = p.noise(x * noiseFrequency, y * noiseFrequency, time)
      const angle = field * p.TWO_PI * (1.2 + settings.complexity / 22)
      const length = (8 + p.noise(index * 0.08, time + 4) * 35) * sizeMultiplier
      const hueOffset = ((index / Math.max(1, count - 1)) - 0.5) * settings.colorSpread
      p.stroke(wrapHue(settings.hue + hueOffset), 72, isDark ? 98 : 74, 0.74)
      p.line(x, y, x + p.cos(angle) * length, y + p.sin(angle) * length)
    }
  } else if (settings.pattern === 'orbit bloom') {
    p.noFill()
    p.push()
    p.translate(p.width / 2, p.height / 2)
    const maxRadius = Math.min(p.width, p.height) * (0.18 + settings.scale / 450)
    const orbitComplexity = 1 + settings.complexity / 26
    for (let index = 0; index < count; index += 1) {
      const phase = p.random(p.TWO_PI)
      const radius = p.noise(index * noiseFrequency * 13, time) * maxRadius
      const x = p.cos(phase + time * (3 + orbitComplexity)) * radius
      const y = p.sin(phase * orbitComplexity + time * 2.6) * radius * 0.72
      const hueOffset = ((index / Math.max(1, count - 1)) - 0.5) * settings.colorSpread
      p.stroke(wrapHue(settings.hue + hueOffset), 68, isDark ? 98 : 76, 0.62)
      p.circle(x, y, (3 + p.noise(index * 0.12, time + 9) * 14) * sizeMultiplier)
    }
    p.pop()
  } else {
    p.noFill()
    const ribbons = Math.max(3, Math.round(settings.density / 7))
    const pointSpacing = Math.max(5, 22 - Math.round(settings.density / 8))
    const amplitude = p.height * Math.min(0.46, 0.09 + settings.scale / 330)
    for (let ribbon = 0; ribbon < ribbons; ribbon += 1) {
      const hueOffset = ((ribbon / Math.max(1, ribbons - 1)) - 0.5) * settings.colorSpread
      p.stroke(wrapHue(settings.hue + hueOffset), 72, isDark ? 94 : 70, 0.78)
      p.beginShape()
      for (let x = -pointSpacing * 2; x <= p.width + pointSpacing * 2; x += pointSpacing) {
        const base = ((ribbon + 1) / (ribbons + 1)) * p.height
        const field = p.noise(x * noiseFrequency, ribbon * 0.31, time)
        p.splineVertex(x, base + (field - 0.5) * amplitude * 2)
      }
      p.endShape()
    }
  }

  p.noStroke()
  p.fill(foreground[0], foreground[1], foreground[2], 0.9)
  p.textSize(13)
  p.text(
    `${settings.pattern}  ·  seed ${settings.seed}  ·  ${settings.density} marks  ·  scale ${settings.scale}`,
    18,
    p.height - 18,
  )
  p.fill(settings.hue, 70, isDark ? 98 : 78, 1)
  p.circle(p.width - 24, 24, 10 + settings.strokeWeight)
}

function exportedSketchSource(settings: P5Settings, theme: P5LabProps['theme']) {
  return `// Generated by the disposable OSA p5 Lab.
// Paste into https://editor.p5js.org/ or a p5.js project.
const settings = ${JSON.stringify({ ...settings, theme }, null, 2)};

function wrapHue(value) {
  return ((value % 360) + 360) % 360;
}

function setup() {
  createCanvas(900, 560);
  pixelDensity(Math.min(window.devicePixelRatio, 2));
  colorMode(HSB, 360, 100, 100, 1);
  strokeCap(ROUND);
}

function draw() {
  const isDark = settings.theme === 'dark';
  const backgroundColor = isDark ? [225, 30, 8] : [215, 12, 98];
  const foreground = isDark ? [270, 5, 98] : [215, 45, 17];
  const backgroundAlpha = 1 - (settings.trails / 100) * 0.94;
  const count = Math.round(24 + settings.density * 2.35);
  const time = frameCount * settings.speed * 0.00012;
  const sizeMultiplier = 0.25 + settings.scale / 55;
  const noiseFrequency = 0.0015 + settings.complexity * 0.00014;

  background(...backgroundColor, backgroundAlpha);
  randomSeed(settings.seed);
  noiseSeed(settings.seed);
  strokeWeight(settings.strokeWeight);

  if (settings.pattern === 'flow field') {
    for (let index = 0; index < count; index += 1) {
      const x = random(width);
      const y = random(height);
      const field = noise(x * noiseFrequency, y * noiseFrequency, time);
      const angle = field * TWO_PI * (1.2 + settings.complexity / 22);
      const length = (8 + noise(index * 0.08, time + 4) * 35) * sizeMultiplier;
      const hueOffset = (index / Math.max(1, count - 1) - 0.5) * settings.colorSpread;
      stroke(wrapHue(settings.hue + hueOffset), 72, isDark ? 98 : 74, 0.74);
      line(x, y, x + cos(angle) * length, y + sin(angle) * length);
    }
  } else if (settings.pattern === 'orbit bloom') {
    noFill();
    push();
    translate(width / 2, height / 2);
    const maxRadius = Math.min(width, height) * (0.18 + settings.scale / 450);
    const orbitComplexity = 1 + settings.complexity / 26;
    for (let index = 0; index < count; index += 1) {
      const phase = random(TWO_PI);
      const radius = noise(index * noiseFrequency * 13, time) * maxRadius;
      const x = cos(phase + time * (3 + orbitComplexity)) * radius;
      const y = sin(phase * orbitComplexity + time * 2.6) * radius * 0.72;
      const hueOffset = (index / Math.max(1, count - 1) - 0.5) * settings.colorSpread;
      stroke(wrapHue(settings.hue + hueOffset), 68, isDark ? 98 : 76, 0.62);
      circle(x, y, (3 + noise(index * 0.12, time + 9) * 14) * sizeMultiplier);
    }
    pop();
  } else {
    noFill();
    const ribbons = Math.max(3, Math.round(settings.density / 7));
    const pointSpacing = Math.max(5, 22 - Math.round(settings.density / 8));
    const amplitude = height * Math.min(0.46, 0.09 + settings.scale / 330);
    for (let ribbon = 0; ribbon < ribbons; ribbon += 1) {
      const hueOffset = (ribbon / Math.max(1, ribbons - 1) - 0.5) * settings.colorSpread;
      stroke(wrapHue(settings.hue + hueOffset), 72, isDark ? 94 : 70, 0.78);
      beginShape();
      for (let x = -pointSpacing * 2; x <= width + pointSpacing * 2; x += pointSpacing) {
        const base = ((ribbon + 1) / (ribbons + 1)) * height;
        const field = noise(x * noiseFrequency, ribbon * 0.31, time);
        splineVertex(x, base + (field - 0.5) * amplitude * 2);
      }
      endShape();
    }
  }

  noStroke();
  fill(...foreground, 0.9);
  textSize(13);
  text(\`${'${settings.pattern}'} · seed ${'${settings.seed}'} · ${'${settings.density}'} marks · scale ${'${settings.scale}'}\`, 18, height - 18);
  fill(settings.hue, 70, isDark ? 98 : 78, 1);
  circle(width - 24, 24, 10 + settings.strokeWeight);
}
`
}

/** A disposable instance-mode p5 experiment. It has no OSA board connection. */
export function P5Lab({ theme }: P5LabProps) {
  const hostRef = useRef<HTMLDivElement>(null)
  const sketchRef = useRef<p5 | null>(null)
  const resizeFrameRef = useRef<number | null>(null)
  const instanceTokenRef = useRef(0)
  const needsClearRef = useRef(true)

  const [pattern, setPattern] = useState<PatternName>('flow field')
  const [seed, setSeed] = useState(OSA_DEFAULT_SEED)
  const [density, setDensity] = useState(42)
  const [speed, setSpeed] = useState(55)
  const [scale, setScale] = useState(52)
  const [complexity, setComplexity] = useState(46)
  const [strokeWeight, setStrokeWeight] = useState(1.4)
  const [hue, setHue] = useState(285)
  const [colorSpread, setColorSpread] = useState(85)
  const [trails, setTrails] = useState(18)
  const [playing, setPlaying] = useState(true)

  const settings = useMemo<P5Settings>(
    () => ({ pattern, seed, density, speed, scale, complexity, strokeWeight, hue, colorSpread, trails }),
    [colorSpread, complexity, density, hue, pattern, scale, seed, speed, strokeWeight, trails],
  )
  const source = useMemo(() => exportedSketchSource(settings, theme), [settings, theme])
  const settingsRef = useRef(settings)
  const themeRef = useRef(theme)
  const playingRef = useRef(playing)

  useEffect(() => {
    const host = hostRef.current
    if (!host) return

    // StrictMode mounts effects twice in development. Empty this dedicated host
    // before attaching p5 so a stale constructor can never leave a second canvas.
    host.replaceChildren()
    const instanceToken = instanceTokenRef.current + 1
    instanceTokenRef.current = instanceToken
    let disposed = false

    const sizeCanvas = () => {
      const width = Math.max(280, Math.floor(host.clientWidth))
      const measuredHeight = Math.floor(host.clientHeight)
      const height = Math.max(360, measuredHeight || Math.min(680, Math.round(width * 0.62)))
      return { width, height }
    }

    const sketch = new p5((p) => {
      p.setup = () => {
        // p5 may defer setup until after StrictMode has already cleaned up this
        // effect. A retired instance must not be allowed to append a canvas.
        if (disposed || instanceTokenRef.current !== instanceToken) {
          p.noLoop()
          p.remove()
          return
        }
        const size = sizeCanvas()
        const renderer = p.createCanvas(size.width, size.height)
        renderer.elt.setAttribute('aria-label', 'Interactive p5 generative pattern')
        p.pixelDensity(Math.min(window.devicePixelRatio, 2))
        p.colorMode(p.HSB, 360, 100, 100, 1)
        if (!playingRef.current) p.noLoop()
      }

      p.draw = () => {
        if (disposed || instanceTokenRef.current !== instanceToken) {
          p.noLoop()
          return
        }
        const currentSettings = settingsRef.current
        if (!currentSettings) return
        const clearBeforeDrawing = needsClearRef.current
        needsClearRef.current = false
        drawPattern(p, currentSettings, themeRef.current, clearBeforeDrawing)
      }
    }, host)

    sketchRef.current = sketch

    const resizeObserver = new ResizeObserver(() => {
      if (resizeFrameRef.current !== null) cancelAnimationFrame(resizeFrameRef.current)
      resizeFrameRef.current = requestAnimationFrame(() => {
        resizeFrameRef.current = null
        if (sketchRef.current !== sketch) return
        const size = sizeCanvas()
        if (sketch.width === size.width && sketch.height === size.height) return
        needsClearRef.current = true
        sketch.resizeCanvas(size.width, size.height, true)
        if (!playingRef.current) sketch.redraw()
      })
    })
    resizeObserver.observe(host)

    return () => {
      disposed = true
      if (instanceTokenRef.current === instanceToken) instanceTokenRef.current += 1
      resizeObserver.disconnect()
      if (resizeFrameRef.current !== null) {
        cancelAnimationFrame(resizeFrameRef.current)
        resizeFrameRef.current = null
      }
      sketch.remove()
      if (sketchRef.current === sketch) sketchRef.current = null
      host.replaceChildren()
    }
  }, [])

  useEffect(() => {
    settingsRef.current = settings
    themeRef.current = theme
    needsClearRef.current = true
    if (!playingRef.current) sketchRef.current?.redraw()
  }, [settings, theme])

  useEffect(() => {
    playingRef.current = playing
    const sketch = sketchRef.current
    if (!sketch) return
    if (playing) {
      sketch.loop()
    } else {
      sketch.noLoop()
      needsClearRef.current = true
      sketch.redraw()
    }
  }, [playing])

  const regenerate = () => setSeed(Math.floor(Math.random() * 999_999) + 1)
  const exportPng = () => sketchRef.current?.saveCanvas(`osa-${pattern.replaceAll(' ', '-')}-${seed}`, 'png')
  const exportSource = () => downloadBlob(new Blob([source], { type: 'text/javascript' }), 'osa-p5-sketch.js')

  return (
    <section className={`p5-lab p5-lab--${theme}`} aria-label="p5 generative pattern lab">
      <header className="p5-lab__header">
        <div>
          <h2>p5 pattern lab</h2>
          <p>Change the rules behind a full-canvas, seeded drawing.</p>
        </div>
        <div className="p5-lab__actions">
          <button type="button" onClick={() => setPlaying((value) => !value)}>{playing ? 'pause' : 'play'}</button>
          <button type="button" onClick={regenerate}>regenerate</button>
          <button type="button" onClick={exportPng}>export PNG</button>
          <button type="button" onClick={exportSource}>source JS</button>
        </div>
      </header>

      <div className="p5-lab__layout">
        <aside className="p5-lab__controls" aria-label="p5 pattern controls">
          <fieldset>
            <legend>composition</legend>
            <label>
              preset
              <select value={pattern} onChange={(event) => setPattern(event.target.value as PatternName)}>
                {PATTERNS.map((name) => <option key={name}>{name}</option>)}
              </select>
            </label>
            <label>
              seed
              <input type="number" min="1" max="999999" value={seed} onChange={(event) => setSeed(Math.max(1, Number(event.target.value) || 1))} />
            </label>
          </fieldset>

          <fieldset>
            <legend>structure</legend>
            <label>density <output>{density}</output><input type="range" min="8" max="100" value={density} onChange={(event) => setDensity(Number(event.target.value))} /></label>
            <label>scale <output>{scale}</output><input type="range" min="10" max="120" value={scale} onChange={(event) => setScale(Number(event.target.value))} /></label>
            <label>complexity <output>{complexity}</output><input type="range" min="0" max="100" value={complexity} onChange={(event) => setComplexity(Number(event.target.value))} /></label>
            <label>motion <output>{speed}</output><input type="range" min="0" max="100" value={speed} onChange={(event) => setSpeed(Number(event.target.value))} /></label>
          </fieldset>

          <fieldset>
            <legend>appearance</legend>
            <label>line weight <output>{strokeWeight.toFixed(1)}</output><input type="range" min="0.4" max="6" step="0.2" value={strokeWeight} onChange={(event) => setStrokeWeight(Number(event.target.value))} /></label>
            <label>hue <output>{hue}°</output><input type="range" min="0" max="359" value={hue} onChange={(event) => setHue(Number(event.target.value))} /></label>
            <label>color spread <output>{colorSpread}°</output><input type="range" min="0" max="240" value={colorSpread} onChange={(event) => setColorSpread(Number(event.target.value))} /></label>
            <label>trails <output>{trails}%</output><input type="range" min="0" max="95" value={trails} onChange={(event) => setTrails(Number(event.target.value))} /></label>
          </fieldset>

          <p className="p5-lab__note">
            Pause to inspect a frame. Every control still redraws while paused; the seed makes the same setup repeatable.
          </p>
        </aside>
        <div className="p5-lab__stage" ref={hostRef} />
      </div>
    </section>
  )
}
